spring:
  datasource:
    url: jdbc:mysql://localhost/development
    driverClassName: com.mysql.cj.jdbc.Driver
    username: user
    password: password
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
